#!/usr/bin/env python3
from pathlib import Path
import shutil
import sys


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("usage: patch_firmware.py <flipper-firmware-dir>")

    root = Path(sys.argv[1]).resolve()
    project = Path(__file__).resolve().parents[1]

    source_app = project / "overlay" / "applications_user" / "r2d2_controller"
    target_app = root / "applications_user" / "r2d2_controller"
    if target_app.exists():
        shutil.rmtree(target_app)
    shutil.copytree(source_app, target_app)

    gap_file = root / "targets" / "f7" / "ble_glue" / "gap.c"
    gap_text = gap_file.read_text(encoding="utf-8")
    needle = "aci_gap_init(\n        GAP_PERIPHERAL_ROLE,"
    replacement = "aci_gap_init(\n        (GAP_PERIPHERAL_ROLE | GAP_CENTRAL_ROLE),"
    if needle not in gap_text:
        raise RuntimeError("Could not find GAP role initialization to patch")
    gap_file.write_text(gap_text.replace(needle, replacement, 1), encoding="utf-8")

    options = root / "fbt_options_local.py"
    options.write_text(
        "# Generated by the R2-D2 standalone controller build.\n"
        'FIRMWARE_ORIGIN = "R2D2"\n'
        "COMPACT = 1\n"
        "DEBUG = 0\n"
        'COPRO_OB_DATA = "scripts/ob_custradio.data"\n'
        'COPRO_STACK_BIN = "stm32wb5x_BLE_Stack_full_fw.bin"\n'
        'COPRO_STACK_TYPE = "ble_full"\n'
        'FIRMWARE_APPS["default"].append("r2d2_controller")\n',
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
